### ISSUE TITLE
Recognized Beer default값 조정

### ISSUE THREAD

**Issue by sxxjxxhxxn** [minlee077/BARS#2]
현재 default값 : Cass (아무 사진 찍으면 Cass로 나옴)
일정 match ratio 이하이면 다시 사진 찍도록 해야될 듯 합니다.

**Comment by minlee077** [comment]
기존 학습 데이터에 비교적 cass가 많아 학습된 모델이 불확실한 대상에 대해 cass label에 높은 점수를 주는 것으로 보입니다.
말씀하신대로 추후 릴리스에서는 부족한 데이터를 충분히 확보하여 분류 모델을 개선하고 예측한 대상의 score가 일정수준 이하면 사진을 다시 찍도록 하는 것이 좋을것 같습니다.
